// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOoPslL4yIj7_GDT35m_7KIW7AHq3_zxk',
    appId: '1:765638595016:web:b40873f03801642881f0fd',
    messagingSenderId: '765638595016',
    projectId: 'proyecto2-9b89c',
    authDomain: 'proyecto2-9b89c.firebaseapp.com',
    storageBucket: 'proyecto2-9b89c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2nLKSp5byXEoBOtCOHBHjGlenHJ0LMb0',
    appId: '1:765638595016:android:e88c53fe8cd4f0cd81f0fd',
    messagingSenderId: '765638595016',
    projectId: 'proyecto2-9b89c',
    storageBucket: 'proyecto2-9b89c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2KqMmbomQmbOxegLKIlcxDNyUT5JwFZ0',
    appId: '1:765638595016:ios:306290a33fd4080d81f0fd',
    messagingSenderId: '765638595016',
    projectId: 'proyecto2-9b89c',
    storageBucket: 'proyecto2-9b89c.appspot.com',
    iosClientId: '765638595016-o68tbm655pm68ir26h0v8hd5dtocj7lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400554Fb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2KqMmbomQmbOxegLKIlcxDNyUT5JwFZ0',
    appId: '1:765638595016:ios:306290a33fd4080d81f0fd',
    messagingSenderId: '765638595016',
    projectId: 'proyecto2-9b89c',
    storageBucket: 'proyecto2-9b89c.appspot.com',
    iosClientId: '765638595016-o68tbm655pm68ir26h0v8hd5dtocj7lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400554Fb',
  );
}
